//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitZona
{
    using System;
    using System.Collections.Generic;
    
    public partial class prostor_termin
    {
        public int termin_id { get; set; }
        public int sportski_prostor_id { get; set; }
        public Nullable<byte> slobodan { get; set; }
    
        public virtual Sportski_prostor Sportski_prostor { get; set; }
        public virtual Termin Termin { get; set; }
    }
}
