//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpraviteljIzradePrograma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.Rezervacija_opreme = new HashSet<Rezervacija_opreme>();
        }
    
        public int rezervacija_id { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public System.TimeSpan vrijeme_od { get; set; }
        public Nullable<int> duljina_rezervacija_sati { get; set; }
        public Nullable<byte> plaćena { get; set; }
        public Nullable<int> korisnik_id { get; set; }
        public Nullable<int> sportski_prostor_id { get; set; }
        public Nullable<int> zaposlenik_id { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija_opreme> Rezervacija_opreme { get; set; }
        public virtual Sportski_prostor Sportski_prostor { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
